use_frameworks!

platform :ios, '10.0'

target 'YYBase_Example' do
  pod 'YYBase', :path => '/Users/wangheng/Desktop/cocoapods/YYBase'

  target 'YYBase_Tests' do
    inherit! :search_paths

    
  end
end

